[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version = "1.0.0-alpha.7"
update_changelog_on_bump = false
major_version_zero = false
version_files = [
    "backend/pyproject.toml:version",
    "frontend/package.json:\"version\"",
]
