"""Add Phase 1 data models

Revision ID: c18ff4a97d6e
Revises:
Create Date: 2026-03-09 02:01:32.769386

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c18ff4a97d6e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ocr_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_name"),
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("region_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("region_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("region_key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("unique_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("year", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_name"),
    )
    op.create_table(
        "ocr_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ocr_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_name"),
    )
    op.create_table(
        "registered_voters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("name_data", sa.JSON(), nullable=True),
        sa.Column("address_data", sa.JSON(), nullable=True),
        sa.Column("other_field_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_registered_voters_region_id"),
        "registered_voters",
        ["region_id"],
        unique=False,
    )
    op.create_table(
        "matcher_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column(
            "current_status",
            sa.Enum(
                "NOT_STARTED",
                "OCR_PENDING",
                "OCR_STARTED",
                "OCR_COMPLETED",
                "OCR_FAILED",
                "OCR_TIMEOUT",
                "MATCHING_PENDING",
                "MATCHING",
                "MATCHING_COMPLETED",
                "MATCHING_ERROR",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("started_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("ended_on", sa.DateTime(), nullable=True),
        sa.Column("error_data", sa.JSON(), nullable=True),
        sa.Column("success_data", sa.JSON(), nullable=True),
        sa.Column("started_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_matcher_jobs_campaign_id"),
        "matcher_jobs",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "petition_scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column(
            "original_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("stored_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_path"),
    )
    op.create_index(
        op.f("ix_petition_scans_campaign_id"),
        "petition_scans",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_petition_scans_file_hash"),
        "petition_scans",
        ["file_hash"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "session_type", sa.Enum("DEMO", "REAL", name="sessiontype"), nullable=False
        ),
        sa.Column("snapshot_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ocr_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("matcher_job_id", sa.Integer(), nullable=False),
        sa.Column("provider_job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ocr_model_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "OCR_PENDING",
                "OCR_STARTED",
                "OCR_COMPLETED",
                "OCR_FAILED",
                "OCR_TIMEOUT",
                "MATCHING_PENDING",
                "MATCHING",
                "MATCHING_COMPLETED",
                "MATCHING_ERROR",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("started_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.Column("ended_on", sa.DateTime(), nullable=True),
        sa.Column("error_data", sa.JSON(), nullable=True),
        sa.Column("success_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matcher_job_id"],
            ["matcher_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ocr_model_id"],
            ["ocr_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ocr_jobs_matcher_job_id"), "ocr_jobs", ["matcher_job_id"], unique=False
    )
    op.create_table(
        "petition_crops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("crop_index", sa.Integer(), nullable=False),
        sa.Column("stored_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("crop_coordinates", sa.JSON(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["petition_scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_path"),
    )
    op.create_table(
        "ocr_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crop_id", sa.Integer(), nullable=False),
        sa.Column("ocr_job_id", sa.Integer(), nullable=False),
        sa.Column("extracted_text", sa.JSON(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crop_id"],
            ["petition_crops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ocr_job_id"],
            ["ocr_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crop_id"),
    )
    op.create_table(
        "match_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ocr_result_id", sa.Integer(), nullable=False),
        sa.Column("matcher_job_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("voter_id", sa.Integer(), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column(
            "confidence_level",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="confidencelevel"),
            nullable=False,
        ),
        sa.Column("field_scores", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matcher_job_id"],
            ["matcher_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ocr_result_id"],
            ["ocr_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voter_id"],
            ["registered_voters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match_results")
    op.drop_table("ocr_results")
    op.drop_table("petition_crops")
    op.drop_index(op.f("ix_ocr_jobs_matcher_job_id"), table_name="ocr_jobs")
    op.drop_table("ocr_jobs")
    op.drop_index(op.f("ix_matcher_jobs_campaign_id"), table_name="matcher_jobs")
    op.drop_table("matcher_jobs")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_petition_scans_file_hash"), table_name="petition_scans")
    op.drop_index(op.f("ix_petition_scans_campaign_id"), table_name="petition_scans")
    op.drop_table("petition_scans")
    op.drop_table("ocr_models")
    op.drop_table("ocr_providers")
    op.drop_index(
        op.f("ix_registered_voters_region_id"), table_name="registered_voters"
    )
    op.drop_table("registered_voters")
    op.drop_table("campaigns")
    op.drop_table("regions")
    op.drop_table("users")
    # Drop ENUM types manually (PostgreSQL doesn't auto-drop them)
    op.execute("DROP TYPE IF EXISTS confidencelevel")
    op.execute("DROP TYPE IF EXISTS sessiontype")
    op.execute("DROP TYPE IF EXISTS jobstatus")
    # ### end Alembic commands ###
